#!/bin/bash
# comment the lines of the services you do not need to be started on the group
# you may run this file as ./gps_bundle start|stop|restart
# allways use absolute paths

#echo "starting/stopping logger"
# dont need logger now
#python3 /home/pi/gps_tracker/d_gps_logger.py $1

HOME_DIR="/home/pi/gps_tracker/"
PID_CLIENT=$(ps -ef|grep d_gps_stream_client.py|grep -v grep|awk '{print $2}'|tail -1)
PID_SERVER=$(ps -ef|grep gps_stream_server.py|grep -v grep|awk '{print $2}'|tail -1)

# Remove later
cd $HOME_DIR

case "$1" in
        start)
		if [ -z "$PID_SERVER" ]; then
		  echo "starting server"
		  python3 /home/pi/gps_tracker/gps_stream_server.py &
		  sleep 1
		else
		  echo "server already running"
		fi

		if [ -z "$PID_CLIENT" ]; then
		  echo "starting stream client lan"
		  # delete eny leftovers from unclean shutdown/restart
		  if [ -e /tmp/d-gps-stream-client*.pid ]; then 
		    rm -rf /tmp/d-gps-stream-client*.pid
		  fi
	 	  python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I) 2345 start
		else
		  echo "client already running"
		fi
                ;;
        stop)
		if [ -n "$PID_CLIENT" ]; then 
		  echo "stopping client"
		  python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I) 2345 stop
		  else echo "client is already stopped"
		fi

		if [ -n "$PID_SERVER" ]; then 
		  echo "stopping server"
		  kill $PID_SERVER
		  else echo "server is already stopped"
		fi

                ;;
	status)
		if [ -z "$PID_CLIENT" ]; then echo "Client is not running"; EXIT_CODE=1; else EXIT_CODE=0; fi
		if [ -z "$PID_SERVER" ]; then echo "Server is not running"; EXIT_CODE=1; else EXIT_CODE=0; fi

		if [ $EXIT_CODE -ne 1 ]; then
		  echo "client and server are running"
		  exit $EXIT_CODE
		else
		  exit 1
		fi
		;;
        *)
		echo "supply start or stop argument"
                ;;
esac

#sleep 1
#python3 /home/pi/gps_tracker/is_my_wan_ip.py 1.2.3.4
#if [ $? = "0" ]; then
#   #this is not a U-turn!
#   echo "starting/stopping stream client internet"
#   python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I) 2345 $1
#   sleep 1
#fi

#echo "start/stop email on internet"
#python3 /home/pi/gps_tracker/d_send_email_on_internet.py $1
#sleep 1
#echo "start/stop fix email notify"
#python3 /home/pi/gps_tracker/d_send_email_on_fix.py $1

