#!/bin/bash
# comment the lines of the services you do not need to be started on the group
# you may run this file as ./gps_bundle start|stop|restart
# allways use absolute paths

#echo "starting/stopping logger"
# dont need logger now
#python3 /home/pi/gps_tracker/d_gps_logger.py $1

HOME_DIR="/home/pi/gps_tracker/"
PID_CLIENT=$(ps -ef|grep d_gps_stream_client.py|grep -v grep|awk '{print $2}'|tail -1)
PID_SERVER=$(ps -ef|grep gps_stream_server.py|grep -v grep|awk '{print $2}'|tail -1)

# Remove later
cd $HOME_DIR

case "$1" in
        start)
		if [ -z "$PID_SERVER" ]; then
		  echo "$(date) - starting server"
		  python3 /home/pi/gps_tracker/gps_stream_server.py &
		  sleep 1
		else
		  echo "$(date) - server already running"
		fi

		if [ -z "$PID_CLIENT" ]; then
		  echo "$(date) - starting stream client lan"
		  # delete eny leftovers from unclean shutdown/restart
		  if [ -e /tmp/d-gps-stream-client*.pid ]; then 
		    rm -rf /tmp/d-gps-stream-client*.pid
		  fi
	 	  python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I|cut -d " " -f1) 2345 start
		else
		  echo "$(date) - client already running"
		fi
                ;;
        stop)
		if [ -n "$PID_CLIENT" ]; then 
		  echo "$(date) - stopping client"
		  python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I|cut -d " " -f1) 2345 stop
		  else echo "$(date) - client is already stopped"
		fi

		if [ -n "$PID_SERVER" ]; then 
		  echo "$(date) - stopping server"
		  kill $PID_SERVER
		  else echo "$(date) - server is already stopped"
		fi

                ;;
	status)
		if [ -z "$PID_CLIENT" ]; then echo "$(date) - Client is not running"; EXIT_CODE_CLIENT=1; else EXIT_CODE_CLIENT=0; fi
		if [ -z "$PID_SERVER" ]; then echo "$(date) - Server is not running"; EXIT_CODE_SERVER=1; else EXIT_CODE_SERVER=0; fi

		if [ $EXIT_CODE_CLIENT -ne 1 ] && [ $EXIT_CODE_SERVER -ne 1 ]; then
		  echo "$(date) - client and server are running"
		  exit 0
		else
		  exit 1
		fi
		;;
	restart)
		$0 stop
		$0 start
		;;
        *)
		echo "supply start or stop argument"
                ;;
esac

#sleep 1
#python3 /home/pi/gps_tracker/is_my_wan_ip.py 1.2.3.4
#if [ $? = "0" ]; then
#   #this is not a U-turn!
#   echo "starting/stopping stream client internet"
#   python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I) 2345 $1
#   sleep 1
#fi

#echo "start/stop email on internet"
#python3 /home/pi/gps_tracker/d_send_email_on_internet.py $1
#sleep 1
#echo "start/stop fix email notify"
#python3 /home/pi/gps_tracker/d_send_email_on_fix.py $1

