#!/bin/bash
# comment the lines of the services you do not need to be started on the group
# you may run this file as ./gps_bundle start|stop|restart
# allways use absolute paths

#echo "starting/stopping logger"
# dont need logger now
#python3 /home/pi/gps_tracker/d_gps_logger.py $1

HOME_DIR="/home/pi/gps_tracker/"

case "$1" in
        start)
		echo "starting/stopping server"
		cd $HOME_DIR
		python3 /home/pi/gps_tracker/gps_stream_server.py 2>&1 &
		sleep 10

		echo "starting/stopping stream client lan"
		# delete eny leftovers from unclean shutdown/restart
		if [ -e /tmp/d-gps-stream-client*.pid ]; then 
			rm -rf /tmp/d-gps-stream-client*.pid
		fi
		python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I) 2345 start
                ;;
        stop)
		cd $HOME_DIR
		python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I) 2345 stop
                ;;
        *)
		echo "supply start or stop argument"
                ;;
esac

#sleep 1
#python3 /home/pi/gps_tracker/is_my_wan_ip.py 1.2.3.4
#if [ $? = "0" ]; then
#   #this is not a U-turn!
#   echo "starting/stopping stream client internet"
#   python3 /home/pi/gps_tracker/d_gps_stream_client.py $(hostname -I) 2345 $1
#   sleep 1
#fi

#echo "start/stop email on internet"
#python3 /home/pi/gps_tracker/d_send_email_on_internet.py $1
#sleep 1
#echo "start/stop fix email notify"
#python3 /home/pi/gps_tracker/d_send_email_on_fix.py $1

